<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="4lun">

  <!-- Constants -->
  <xacro:property name="base_size" value="0.4" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="wheel_base_x" value="0.3" />
  <xacro:property name="wheel_base_y" value="0.3" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_size} ${base_size} 0.1"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_size} ${base_size} 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix x_offset y_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_offset} ${y_offset} 0" rpy="-1.5707 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="front_left" x_offset="${wheel_base_x/2}" y_offset="${wheel_base_y/2}" />
  <xacro:wheel prefix="front_right" x_offset="${wheel_base_x/2}" y_offset="-${wheel_base_y/2}" />
  <xacro:wheel prefix="rear_left" x_offset="-${wheel_base_x/2}" y_offset="${wheel_base_y/2}" />
  <xacro:wheel prefix="rear_right" x_offset="-${wheel_base_x/2}" y_offset="-${wheel_base_y/2}" />

  <!-- Gazebo Mecanum Drive Plugin -->
  <gazebo>
    <plugin name="mecanum_drive_controller" filename="libgazebo_ros_mecanum_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      
      <front_left_joint>front_left_wheel_joint</front_left_joint>
      <front_right_joint>front_right_wheel_joint</front_right_joint>
      <rear_left_joint>rear_left_wheel_joint</rear_left_joint>
      <rear_right_joint>rear_right_wheel_joint</rear_right_joint>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <update_rate>30.0</update_rate>
    </plugin>
  </gazebo>

</robot>
